version: "3.8"

services:
  db:
    image: postgres:13
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - "postgres"
      - "-c"
      - "max_connections=40"
      - "-c"
      - "shared_buffers=16GB"
      - "-c"
      - "effective_cache_size=48GB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=500"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=104857kB"
      - "-c"
      - "min_wal_size=4GB"
      - "-c"
      - "max_wal_size=16GB"

volumes:
  db-data:
