version: "3.8"

x-app: &default-app
  restart: "unless-stopped"
  logging:
      driver: "json-file"
      options:
        max-size: "2048m"

services:
  jupyter-lab:
    <<: *default-app
    image: jupyter/datascience-notebook
    expose:
      - "8888"
    volumes:
      - jupyter-lab-work:/home/jovyan/work
    links:
      - db
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=KsL6EsCygGQFSLkw
      - LETSENCRYPT_HOST=lab.rhizo.me
      - VIRTUAL_HOST=lab.rhizo.me

  metabase:
    image: metabase/metabase
    expose:
      - "3000"
    volumes:
      - metabase-data:/data
    links:
      - db
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g
      - MB_DB_FILE=/data/metabase.db
      - LETSENCRYPT_HOST=metabase.rhizo.me
      - VIRTUAL_HOST=metabase.rhizo.me

  db:
    image: timescale/timescaledb:latest-pg13
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=timescaledb"
      - "-c"
      - "shared_buffers=16GB"
      - "-c"
      - "effective_cache_size=48081MB"
      - "-c"
      - "maintenance_work_mem=2047MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=500"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=20514kB"
      - "-c"
      - "min_wal_size=512MB"
      - "-c"
      - "max_wal_size=16GB"
      - "-c"
      - "timescaledb.max_background_workers=8"
      - "-c"
      - "max_worker_processes=19"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      - "max_locks_per_transaction=512"
      - "-c"
      - "autovacuum_max_workers=10"
      - "-c"
      - "autovacuum_naptime=10"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: nginxproxy/acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: me@hakanensari.com

volumes:
  jupyter-lab-work:
  db-data:
  metabase-data:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
