version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    links:
      - db
    environment:
      GF_SECURITY_ADMIN_PASSWORD: TKy36eLZ!WL-.Biv@
      GF_USERS_ALLOW_SIGN_UP: "false"
      LETSENCRYPT_EMAIL: hakanensari@gmail.com
      LETSENCRYPT_HOST: grafana.a.lineofflig.ht
      VIRTUAL_HOST: grafana.a.lineofflig.ht

  metabase:
    image: metabase/metabase
    expose:
      - "3000"
    volumes:
      - metabase-data:/data
    links:
      - db
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
      LETSENCRYPT_EMAIL: hakanensari@gmail.com
      LETSENCRYPT_HOST: metabase.a.lineofflig.ht
      MB_DB_FILE: /data/metabase.db
      VIRTUAL_HOST: metabase.a.lineofflig.ht

  db:
    image: timescale/timescaledb:latest-pg13
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=timescaledb"
      - "-c"
      - "shared_buffers=16GB"
      - "-c"
      - "effective_cache_size=48081MB"
      - "-c"
      - "maintenance_work_mem=2047MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=500"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=20514kB"
      - "-c"
      - "min_wal_size=512MB"
      - "-c"
      - "max_wal_size=16GB"
      - "-c"
      - "timescaledb.max_background_workers=8"
      - "-c"
      - "max_worker_processes=19"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      - "max_locks_per_transaction=512"
      - "-c"
      - "autovacuum_max_workers=10"
      - "-c"
      - "autovacuum_naptime=10"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - /etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

volumes:
  db-data:
  grafana-data:
  metabase-data:
  certs:
  html:
  vhost.d:
