DROP MATERIALIZED VIEW IF EXISTS stocks_5m_rth CASCADE;

DROP MATERIALIZED VIEW IF EXISTS etfs_5m_rth CASCADE;

DROP MATERIALIZED VIEW IF EXISTS indexes_5m CASCADE;

DROP MATERIALIZED VIEW IF EXISTS stocks_1d_rth CASCADE;

DROP MATERIALIZED VIEW IF EXISTS etfs_1d_rth CASCADE;

DROP MATERIALIZED VIEW IF EXISTS indexes_1d CASCADE;

DROP TABLE IF EXISTS stocks_1m CASCADE;

DROP TABLE IF EXISTS etfs_1m CASCADE;

DROP TABLE IF EXISTS indexes_1m CASCADE;
